### ISSUE TITLE
Dashboard - Power BI

### ISSUE THREAD

**Issue by AnitaPedernera** [Game-Changers-PF/Proyecto-Final#43]

**Comment by Valen2690** [comment]
Previo a realizar las visualizaciones tenidas en cuenta en el Mockup, se realizaron en Power Query las siguientes transformaciones de datos: 

**all_nba_players_status**
Se realizó filtro a la columna status donde solo se tuvieron en cuenta los jugadores activos.

**Cleaned_draft_history**
Se realizó filtro por season, tomando solo los años 2015 al 2022

**Cleaned_player_average**
Se aplico filtro al status, dejando solo los jugadores activos

**Cleaned_team_details**
Se borro la columna year founded debido a que contenia datos erróneos. Adicional se borraron las columnas nickname, abreviation  y city puesto que en la tabla cleaned team, estos datos ya se encontraban. 
 
También se realizaron transformaciones tales como: 

•Cambio tipo de dato a entero en edad y crear nueva columna con el dato corregido. Nueva columna "edad corregida".
•En peso ponerlo de tipo entero y crear nueva columna, con tipo de dato decimal. 
•Para calcular el porcentaje de partidos ganados, creamos columna con la división entre ganados sobre el total de partidos y crear la columna con tipo %.

Así mismo, se crearon inicialmente las siguientes medidas:

•Edad del jugador = MAX(cleaned_player_average_stats_2015_2022[Edad corregida])
•Puntos totales = (SUMX(cleaned_player_average_stats_2015_2022,3*cleaned_player_average_stats_2015_2022[FG3M])) + (SUMX(cleaned_player_average_stats_2015_2022,2*cleaned_player_average_stats_2015_2022[FGM])) + (SUMX(cleaned_player_average_stats_2015_2022,cleaned_player_average_stats_2015_2022[FTM]))
