### ISSUE TITLE
Creacion de la base de datos

### ISSUE THREAD

**Issue by redsar6** [Game-Changers-PF/Proyecto-Final#5]
Se deben crear las tablas correspondientes a la base de datos.
Con sus respectivas relaciones entre si.

**Comment by redsar6** [comment]
como un pequeño avance realice el filtrado de las tablas player y draft_history con los siguientes criterios.
- Player
Se filtro por jugadores activos en la temporada de interes manteniendo solo el id y full_name
- Draft_History
Se realizo un merge entre esta tabla y la tabla Player, usando como criterio las coincidencias entre jugadores activos de ambas tablas

**Comment by mplaza72** [comment]
buen dia, vi que ya se trabajo sobre las tablas, que tendria que hacer entonces?
