### ISSUE TITLE
Proceso EDA tablas elegidas

### ISSUE THREAD

**Issue by Valen2690** [Game-Changers-PF/Proyecto-Final#8]
Realizar procesos de filtrado por fecha, verificación de nulos, eliminación de columnas que no aporten información relevante y verificación tipo de datos. 

**Valentina**
_player_game_stats_2015_2022
shot_chart_details_2015_2022_

**Ana** 
draft_combine_stats
_player_average_stats_2015_2022
team_

**Mari**
_calendario_partidos_2015_2022
team_details_

**Comment by AnitaPedernera** [comment]
En la limpieza de los datos, tomar año de inicio de temporada para normalizar los datos (para temporada/season). 
Actualización de limpieza tablas: 
Valentina
team
shot_chart_details_2015_2022

Ana
draft_combine_stats
player_average_stats_2015_2022

Mari
calendario_partidos_2015_2022
team_details

Mati
player_game_stats_2015_2022
